# Generated by Django 2.2.7 on 2019-11-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
