# Generated by Django 2.2.7 on 2019-11-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imam', '0002_remove_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='upvotes',
            field=models.IntegerField(default=1),
        ),
    ]
