# Generated by Django 2.2.7 on 2019-11-18 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imam', '0003_script_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
